# Generated by Django 5.0 on 2024-06-08 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='firebaseUID')),
                ('user_name', models.CharField(blank=True, max_length=15, null=True, verbose_name='ユーザー名')),
                ('user_icon', models.ImageField(blank=True, null=True, upload_to='icons/', verbose_name='ユーザーアイコン')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': 'ユーザー情報',
                'db_table': 'users',
            },
        ),
    ]
