# TODO Dockerfileの軽量化
FROM node:lts-alpine as build-stage
WORKDIR /code/
# ENV NODE_ENV=development
COPY package*.json .
RUN npm install
COPY . .
RUN npm run build

# nginxの実行環境をインストール
FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /code/dist/ /usr/share/nginx/html
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]