# TODO Dockerfileの軽量化
FROM node:lts-alpine as build-stage
WORKDIR /code/
RUN npm install -g @quasar/cli
# ENV NODE_ENV=development
COPY package*.json .
RUN npm install
COPY . .
RUN npm run build

# nginxの実行環境をインストール
FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /code/dist/spa /usr/share/nginx/html
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
