FROM node:lts-alpine as build-stage
WORKDIR /code
# node.js の環境変数を定義する
# 本番環境では production
ENV NODE_ENV=development
COPY ../view/asakatu-habit/package*.json ./
RUN npm install
COPY ./view/asakatu-habit/ .
RUN npm run build
EXPOSE 80

FROM nginx:stable-alpine as production-stage
COPY --from=build-stage code/dist/ /usr/share/nginx/html
# COPY nginx_config/nginx.conf /etc/nginx/nginx.conf
# COPY nginx_config/default.conf /etc/nginx/conf.d/default.conf
CMD ["nginx", "-g", "demon off;"]