# Generated by Django 5.0 on 2024-06-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('video_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='ビデオID')),
                ('total_study_time', models.IntegerField(default=0)),
                ('total_new_cards', models.IntegerField(default=0)),
                ('total_learning_cards', models.IntegerField(default=0)),
                ('total_review_cards', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ビデオ',
                'db_table': 'videos',
            },
        ),
    ]
