# Generated by Django 5.0 on 2025-07-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='channel_id',
            field=models.CharField(default='unknown', max_length=100, verbose_name='チャンネルID'),
        ),
    ]
