# Generated by Django 5.0 on 2025-10-05 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel_decks', '0001_initial'),
        ('videos', '0002_videos_channel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='channel_id',
        ),
        migrations.AddField(
            model_name='videos',
            name='channel',
            field=models.ForeignKey(blank=True, db_column='channel_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='channel_decks.channeldecks', to_field='channel_id', verbose_name='チャンネル'),
        ),
    ]
