# Generated by Django 5.0 on 2025-10-06 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_remove_videos_channel_id_videos_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('highlighted_text', models.TextField(verbose_name='ハイライトした部分')),
                ('timestamp', models.FloatField(help_text='字幕の開始時間', verbose_name='タイムスタンプ（秒）')),
                ('meaning_japanese', models.TextField(blank=True, null=True, verbose_name='日本語の意味')),
                ('etymology', models.TextField(blank=True, null=True, verbose_name='語源')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='イメージ画像URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('video', models.ForeignKey(db_column='video_id', on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='videos.videos', verbose_name='ビデオ')),
            ],
            options={
                'verbose_name': 'ハイライト',
                'verbose_name_plural': 'ハイライト',
                'db_table': 'highlights',
                'ordering': ['-created_at'],
            },
        ),
    ]
