# Generated by Django 5.0 on 2025-10-07 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_highlight'),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "ALTER TABLE highlights "
                "ADD COLUMN IF NOT EXISTS image_url VARCHAR(500);"
            ),
            reverse_sql=(
                # 逆マイグレーションでは安全のため何もしない
                "SELECT 1;"
            ),
        ),
    ]
