# Generated by Django 5.0 on 2025-10-07 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_add_image_url_fix'),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "ALTER TABLE IF EXISTS public.highlights "
                "ADD COLUMN IF NOT EXISTS image_url VARCHAR(500);"
            ),
            reverse_sql=(
                "SELECT 1;"
            ),
        ),
    ]
