# Generated by Django 5.0 on 2024-07-08 15:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channeldecks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_id', models.CharField(max_length=100, unique=True, verbose_name='チャンネルID')),
                ('channel_title', models.CharField(max_length=100, verbose_name='チャンネル名')),
                ('channel_icon_url', models.URLField(verbose_name='チャンネルアイコン')),
                ('total_study_time', models.IntegerField(default=0, verbose_name='学習時間')),
                ('total_new_cards', models.IntegerField(default=0, verbose_name='新規')),
                ('total_learning_cards', models.IntegerField(default=0, verbose_name='習得中')),
                ('total_review_cards', models.IntegerField(blank=True, default=0, verbose_name='復習')),
                ('uploads_playlist_id', models.CharField(max_length=100, verbose_name='プレイリストID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'チャンネルデッキ',
                'db_table': 'channel_decks',
            },
        ),
    ]
