FROM node:lts-alpine as build-stage
WORKDIR /view
COPY asakatu-habit/package*.json ./
RUN npm install
COPY . .
RUN npm run build

# FROM nginx:stable-alpine as production-stage
# COPY --from=build-stage /app/dist /usr/share/nginx/html
# COPY nginx_config/nginx.conf /etc/nginx/nginx.conf
# COPY nginx_config/default.conf /etc/nginx/conf.d/default.conf
# EXPOSE 80
# CMD ["nginx", "-g", "demon off;"]